### ISSUE TITLE
Token List on polygon defaults to Aave? Thats weird... should default to MATIC

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2598]
![Screenshot 2023-05-02 at 1 08 58 PM](https://user-images.githubusercontent.com/14945613/235762349-3a4418a1-5b46-4c78-802c-f1066f5504b3.png)

**Comment by MoeNick** [comment]
we set up the sorting manually in admin, @laurenluz asked us to make it sorted alphabetically. 
Now we can fix a token or two at the top and list the rest alphabetically. So in this case we can fix MATIC fixed at the top. 
@mateodaza can you take it?

**Comment by MoeNick** [comment]
Done just with a click in Admin.

**Comment by laurenluz** [comment]
haha omg hilarious issue, and epic execution.

**Comment by laurenluz** [comment]
also I said I think we should make the default token the native token for that chain... and sort the rest alphabetically @MoeNick 

So Polygon --> Matic
Gnosis --> xDAI
Mainnet --> ETH
Celo --> Celo
Optimism --> ETH

**Comment by mateodaza** [comment]
> also I said I think we should make the default token the native token for that chain... and sort the rest alphabetically @MoeNick
> 
> So Polygon --> Matic Gnosis --> xDAI Mainnet --> ETH Celo --> Celo Optimism --> ETH

I'm making this possible on this [pr](https://github.com/Giveth/giveth-dapps-v2/pull/2607)

**Comment by MoeNick** [comment]
@mateodaza 
Its fixed now, please take a look. The currant code can cover it

**Comment by mateodaza** [comment]
@MoeNick I checked in production and it wasn't fixed - if my PR it's not needed then let's not merge. Let's discuss on the call tomorrow 🙌🏼

**Comment by MoeNick** [comment]
Ah it reverted back be carlos migration, 😕

**Comment by mateodaza** [comment]
> Ah it reverted back be carlos migration, 😕

no prob! understood

**Comment by MoeNick** [comment]
@maryjaf please test it on all chains, please repeat the tests on different projects, including CHANGE or GIVINGblick and ordinary projects.

**Comment by maryjaf** [comment]
> olygon --> Matic
> Gnosis --> xDAI
> Mainnet --> ETH
> Celo --> Celo
> Optimism --> ETH

I checked and it's ok
