### ISSUE TITLE
User Story - Rejected project owner reason

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2716]
**As a project owner who has been rejected for verification, I want to know the specific reason why my application was rejected, so that there is clarity. This way I know if it is possible or not and if so, the steps I need to take to make it happen.**

**Current set up:** The project verification team presses 'reject project' in the admin bro and a general email is sent explaining the main reasons why projects usually get rejected. This is the same email that is sent to any project owner whose application gets rejected.

This is what the current email looks like:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/c94288d0-7b53-406c-b483-d8a5a030ada8)

**Ideal set up:** Each time the project verification team rejects an application, we type in the comments section in AdminBro the specific reason the project was rejected and what we would need to see from that project in order to verify it.

- This text should be implemented and reflected in the email using a Segment event in conjunction with Autopilot.

- This text should also be sent as a notification to just that project owner in the notification center in the Giveth UI.

**Comment by laurenluz** [comment]
cc @MoeNick @CarlosQ96

**Comment by MoeNick** [comment]
So to my knowledge you want a flow in Admin to choose the reason and then reject the application, and we send this data to Segment for email. did I get it right?

**Comment by WhyldWanderer** [comment]
We already type the reason in the comments box for each application. 
Is there any way we can use the text in the comment? This would allow us to be much more specific and suggest the things that the project owner needs to do to become eligible.

It looks like this in Adminbro:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/ec770bca-7f23-4698-a20b-f8e1cf7cb1cf)

**Comment by divine-comedian** [comment]
@RamRamez - If we add an attribute in the Ortto activity that can accept a string for "reason" do you think it is possible to retrieve this text from the verification form and send it in the activity event?

**Comment by RamRamez** [comment]
When project is rejected via the AdminJS, we can call Ortto in the same function

**Comment by divine-comedian** [comment]
@RamRamez - Please check on how we can retrieve this reason field from admin js and we can send it along in the "project verification" activity when `verified-status == rejected`

**Comment by RamRamez** [comment]
@divine-comedian I triggered the activity with the reason but the reason is not reflected anywhere in the email content. could you check please?

<img width="976" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/73441857/314f159a-f178-4b75-9ad1-1a9708d177f3">

<img width="622" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/73441857/69c5b6f0-12b7-4257-baed-6cf33b5a59fa">

**Comment by divine-comedian** [comment]
@WhyldWanderer  - can you check into this email and fix the copy to use the reason inside the email's content?

**Comment by WhyldWanderer** [comment]
Sure I can check on this!

@RamRamez how do we enter the reason into adminbro? I don't see a field where we can input this information.
Does it pull it directly from the comments that we leave?

I will do some testing with it today! Thanks for working on this... it has been a wishlist item of the team for a while now and I think it will help project owners to get their projects verified quicker by knowing the reason it was rejected

**Comment by RamRamez** [comment]
> Sure I can check on this!
> 
> @RamRamez how do we enter the reason into adminbro? I don't see a field where we can input this information. Does it pull it directly from the comments that we leave?
> 
> I will do some testing with it today! Thanks for working on this... it has been a wishlist item of the team for a while now and I think it will help project owners to get their projects verified quicker by knowing the reason it was rejected

@WhyldWanderer Yes, exactly, it pulls the last comment here:
https://private-user-images.githubusercontent.com/74267818/242313617-ec770bca-7f23-4698-a20b-f8e1cf7cb1cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDcwMjksIm5iZiI6MTcxOTQwNjcyOSwicGF0aCI6Ii83NDI2NzgxOC8yNDIzMTM2MTctZWM3NzBiY2EtN2YyMy00Njk4LWEyMGItZjhlMWNmN2NiMWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEyNTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZTdkNTJkNDEzYTJhNGM4OWUwMDAwMDEwNWZiZTM1M2ZiMmI5NGY2MWNiYjQ0NjEwN2ExN2FmZDdkZjE1MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TwPUgxPbcVoZBS3oHAimiP58BdwqiJDDJFG_g9_oPYI

So, this is how it works:
1. Select desired project in `Project Verification Form` tab
2. Add your comment (explaining project rejection reason)
3. click `save` on AdminJS
4. click `reject`

**Comment by RamRamez** [comment]
@WhyldWanderer The PRs are merged on staging, I tested but still getting the old template for rejection.
So, whenever the template is updated, please ping me to start testing.

**Comment by WhyldWanderer** [comment]
> @WhyldWanderer The PRs are merged on staging, I tested but still getting the old template for rejection. So, whenever the template is updated, please ping me to start testing.

@RamRamez - the template has been updated.. you can start testing now! thanks so much

**Comment by RamRamez** [comment]
@LatifatAbdullahi please test and verify

[Use these flow please] (https://github.com/Giveth/giveth-dapps-v2/issues/2716#issuecomment-2191642301)

**Comment by LatifatAbdullahi** [comment]
@RamRamez 

**TEST UPDATE**

After rejecting a project, and leaving a some comments, I didnt receive any email notification with the Template showing reasons for rejection, please let me know if there is some where else I should view  it.

![reject](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/bdfc6821-c7b7-4554-81f1-e4ab689a4c7c)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/28142dbd-54fe-49e7-8d74-d9b28aab5172)


Also:

When  I clicked on "Reject Project" from the drop down list, it shows this message, even though the Project status is updated to "Rejected"

![rjt](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/42bde45d-b71b-4c58-b04f-ccfa1d656e76)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/e0dfd5cf-5d3d-4953-834e-cb1f8cd657ab)

**Comment by RamRamez** [comment]
@LatifatAbdullahi The project you are trying to reject is already rejected, that's why you didn't receive any email and you see this error.

You can reject only projects with the status equal `submitted`

**Comment by LatifatAbdullahi** [comment]
@RamRamez 

That is a new project I created for the purpose of rejection.
The status was "submitted" before I rejected it. From my previous comment, I stated it threw an error message but the status updated to "rejected" and I didnt get a notificatio even when the status changed to "rejected".

**Comment by RamRamez** [comment]
@LatifatAbdullahi What error message did you face? maybe it was a temporary error on staging, could you please test again? because I tested the flow you mentioned and it was ok for me.

**Comment by LatifatAbdullahi** [comment]
@RamRamez 

Here is the error
![346276878-e0dfd5cf-5d3d-4953-834e-cb1f8cd657ab](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/dff8ff54-aefc-4a19-8d1d-4cad41aacc14)


I will retest by tomorrow...I work mondays to fridays

**Comment by LatifatAbdullahi** [comment]
@RamRamez 

https://drive.google.com/file/d/1Z-nSdB0sgko0J6QfbkURogpB9RplTOq5/view

I still didn't receive any email with the rejection reason, you can check the video I attached, so I created another project to verify it again.

**Comment by RamRamez** [comment]
Thanks @LatifatAbdullahi for testing. You are right, we had an error on some special cases, related to sorting `comments` by date.
I fixed it.
Could you please test again?

**Comment by LatifatAbdullahi** [comment]
@RamRamez 


When an Admin User rejects a project without adding a comment, we still have this prefix in the email (The submission has been rejected for the following reason(s):   ""). Wouldn't it be better if this comes only when comments are added? @divine-comedian 

In addition: If the Admin User goes back to add a comment or multiple comments and clicks on "save", No subsequent email is sent.

![rr](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/ffbc8d1b-853b-4bfe-af83-032f11a073a5)

**Comment by WhyldWanderer** [comment]
Dont worry @LatifatAbdullahi - The verification team ALWAYS adds comment with the reason before pressing the reject button. It is part of our process and tracking

**Comment by LatifatAbdullahi** [comment]
@WhyldWanderer @RamRamez 
Oh! cool then, since that is the case, After adding comments and rejecting the project, I received an email with the last comment(reason).
![tes](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/7677dc7a-8b03-4510-897c-063fbf2f09dd)

Test status: **Pass**
