### ISSUE TITLE
GivFarm page not updating.. its been 6 minutes

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2782]
<img width="1650" alt="Screenshot 2023-06-21 at 2 59 42 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/458c83ad-7b31-4052-a11b-987bd68c9e07">

I harvested & unstaked for both farms.. then i went and made a Fox/xdai LP and now I can't stake it cause the  values arent updating anywhere.... It needs to update at least every minute... ideally every block... why is it so slow.

**Comment by MoeNick** [comment]
From @mohammadranjbarz :
It's probably subgraph problem ( we have no backend webservice for that) and subgraphs are hanadled by devops guys, I think they can investigate

@mhmdksh can you pls take a look?

**Comment by geleeroyale** [comment]
We also need to look at this warning - the subgraph can't connect to IPFS:

```
Trying again after ipfs.cat failed (attempt #19) with result Err(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(10.0.1.215)), port: None, path: "/api/v0/cat", query: Some("arg=QmeFNBSmDx5ZEVxjZjvuzgG2FRLHLy8Rp5xVGrpTR8Ab18"), fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" })) })
```

**Comment by laurenluz** [comment]
this was resolved ? @geleeroyale

**Comment by geleeroyale** [comment]
The latest posts are not directly related with the issue but still persist. I will open another issue for them. You can close this @laurenluz
