### ISSUE TITLE
Project single page - GIVpower tab - GIVbacks % is wrong on staging

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2865]
I'm testing on staging... and for every project... it's showing "get up to 80% of your donation back".

This number 80% should be different on every project with a different GIVpower allocation. For example, I'm looking at the project ranked #4... it should say get up to 79% back or something.

The project with rank "--" should say "Get up to 50% back" etc.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/cb70c907-4ff9-4635-ade1-67ff6c944256)

**Comment by maryjaf** [comment]
<img width="962" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/dc0694cb-b37c-4d5e-beed-649ac40e9f45">
plz check @alireza-sharifpour

**Comment by laurenluz** [comment]
@alireza-sharifpour - we should round to the nearest whole number.. so that should be 78%.

Also... keep in mind that the absolute max is 80% and the absolute min is 50%

**Comment by divine-comedian** [comment]
fixed decimals 
https://github.com/Giveth/giveth-dapps-v2/commit/ff8c73fbe335fa58610170338ea8758452e0ad80

**Comment by laurenluz** [comment]
On the project owner view... we are still showing 2 decimal places: 
<img width="929" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/85ff1733-cbd3-45b9-b801-118409603431">


@divine-comedian @Vyvy-vi @MohammadPCh - can we fix this quick? should round to the nearest whole number.

**Comment by MohammadPCh** [comment]
@maryjaf It's ready to test.

**Comment by laurenluz** [comment]
looks fixed
