### ISSUE TITLE
There is no record for one of my donation in list of project donations  and user donations 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3974]
I completed donation flow to [metesta project](https://staging.giveth.io/donate/metesta), in the last step I got "failed fetch" error but the success donation and tx hash was shown 
and this is my tx https://optimism-sepolia.blockscout.com/tx/0x6cfa5f98d90bd6d19b6ce58d1f794502d3e5b52082e12d215856f71d59932629

 There isn't any related record for this donation in project donation tab and in my recurring donation list 
 and when I try to donate again to this project I see this message that" I've donated to this project already"
 take a look on below video 
 https://staging.giveth.io/project/testpic101?tab=donations
 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/eac621a5-2827-4aae-bb4d-8e31c20378d8)

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5f075bf1-befa-417e-bcfb-b29b7d0d4fc6

cc: @MohammadPCh @mohammadranjbarz @MoeNick

**Comment by jainkrati** [comment]
This should get solved by draft donation issue https://github.com/Giveth/impact-graph/issues/1463

**Comment by mohammadranjbarz** [comment]
> This should get solved by draft donation issue [Giveth/impact-graph#1463](https://github.com/Giveth/impact-graph/issues/1463)

Exactly

**Comment by maryjaf** [comment]
> and this is my tx https://optimism-sepolia.blockscout.com/tx/0x6cfa5f98d90bd6d19b6ce58d1f794502d3e5b52082e12d215856f71d59932629
> 
> There isn't any related record for this donation in project donation tab and in my recurring donation list and when I try to donate again to this project I see this message that" I've donated to this project already"

After releasing draft donation, this recurring donation isn't still shown in list of project's donation

**Comment by MohammadPCh** [comment]
@maryjaf we cannot recover old donations.

**Comment by maryjaf** [comment]
So I move it to done and check the status of draft donation problem on this issue https://github.com/Giveth/impact-graph/issues/1463
