### ISSUE TITLE
Passport score incorrectly showing as 0 in the backend?

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#3986]
After looking at donation data from past rounds, some Passport scores are showing as 0 despite the user claiming that the banner on our site said they were eligible.

Ex. @SnakeGH's Passport score shows as 0 for the ENS round but he says the banner confirmed his score was above the threshold before donating.

<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWROQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f6d23f2e701e7c8581137e1af90179d622f9a24/image.png" alt="image.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXhOQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c73f09defa885eeb500b4899baa3bc5d0710c3a/Screen%20Shot%202024-04-10%20at%2012.02.38%20PM.png" alt="Screen Shot 2024-04-10 at 12.02.38 PM.png" />

@maryjaf would you be able to investigate and see if you can replicate this problem in staging? cc @jainkrati

**Comment by jainkrati** [comment]
@Meriem-BM pls take this up and if required take guidance from @CarlosQ96

**Comment by jainkrati** [comment]
Already fixed by @CarlosQ96 yesterday.

**Comment by maryjaf** [comment]
> @CarlosQ96 if the user's score is 0... we should be sure that we are not telling them in the banner that they are fine... you know? is this resolved?
> 
> because gitcoin's 3 month expiry thing has always been the case... we just need to make sure that our banners & prompts on the UI are reflecting their score NOW (that is being stored alongside their donation), rather than their score when they clicked the button some time ago.
> 
> I hope that makes sense.

kindly reminder @CarlosQ96 
I'm not sure this issue could be moved to "close" or not

**Comment by laurenluz** [comment]
This issue is still happening and it MUST be fixed before the end of the round!!

Jake reported that in the banners on our dapp, it said his passport score was fine...

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/63696b14-e88a-4bfd-a799-f3aa6b30e2b7)

but on the passport page, his score was not at the threshold...
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/e348760b-7b4b-4f50-a381-7e1cc2194903)

but when Jake went to gitcoin, and refreshed, his score was:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/16bcd11f-3a63-4b2e-8aaa-dbc5e4382661)

then later reflected properly on the dapp as:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/e7e0aacf-f4df-4aa3-8c97-687b1be6d7fb)


So the issue is that our banenrs explaining to the user what's up are giving them TOTALLY WRONG info. We can't tell them their score is fine, if it is in fact not fine.

I don't know where the issue here is coming from, if the solution needs to be changing the banners or if there is a backend fix we can do that solves the problem so the banners are correctly updated.

**Comment by laurenluz** [comment]
Carlos thinks this is likely a frontend issue @jainkrati since the banner is not showing the passport being too low...

What I need is basically that the banner should accurately reflect whatever the passport score we are saving in the backend is.... (I'm not as concerned with making sure our backend is 100% keeping up with gitcoin's autorefresh thing making people's scores go to zero after some time...).

We are saving the passport scores w/ the users' donations at the end of the round so we need to make sure the user is empowered with the correct info on if they need to take action to get their donations qualifying or not.

**Comment by laurenluz** [comment]
@Meriem-BM please check to see if the banner function is accurately reflecting what the backend is saying

**Comment by Meriem-BM** [comment]
@laurenluz @jainkrati, I tried to reproduce this bug, but alas!
The same logic is used for both, banner and passport score page.

**Comment by RamRamez** [comment]
Gitcoin UI is not always reflecting the correct score, because I was comparing the Giveth score and Gitcoin UI score, and Giveth UI was showing zero and and Gitcoin UI was showing 5 for one of my accounts. Then I added another verification in Gitcoin UI to raise my score, and it failed, then my score on Gitcoin UI changed to zero.
So, in my case, Giveth UI was showing the updated score but Gitcoin UI was buggy.

**Comment by maryjaf** [comment]
The result of my test: @RamRamez @Meriem-BM 
-My passport score on dApp is shown: 2.251756
-Required score for current round on stg : 2 
-I see the banner that my user is eligible : "our donations are eligible to be matched!"
-But my score in gitcoin is shown 0 
0xA1179f64638adb613DDAAc32D918EB6BEB824104
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/61e09062-65fa-4394-90ff-55f509cdb6a9)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a5a29a4e-0603-49df-9c09-883f8ebd56a8)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/86ed3c81-0304-493f-969a-27fd0c978f72)

**Comment by RamRamez** [comment]
@maryjaf it's after refresh or before refresh?

**Comment by maryjaf** [comment]
> @maryjaf it's after refresh or before refresh?

Before 
I think what Lauren means is thatو  in this situation taht the user's real score is not what we show in dapp, user should not see the eligible banner either.

**Comment by laurenluz** [comment]
yes! I spoke w/ Ramin about this yesterday. at the very minimum, we need to be absolutely sure that the banner is warning the user if *our* recorded score for them is not above the threshold - Jake reported this as an issue (the banner said he was fine, but his score was like 4.5 with a threshold of 5).

My other concern is that... perhaps the issue w/ Jake's passport score is a symptom of the fact that we are not doing auto-refreshing... and that there is some level of score update that happens maybe after he donates or when he goes to another page, that actually overwrites his "old" score for a "new" one... without the proper warnigs.

I'm not 100% sure what the issue is, but I do know that we are having a discrepency in what the banner is telling users at the time of donation... and what their score saved in our backed at the end of the round is. Griff's donations were excluded from the polygon round... Jake's were excluded from ENS... but both of them reported seeing the banners as "you donation is eligible!"

So there is somewhat of a mystery I hope you can help me solve 🕵️‍♀️ 🕵️‍♂️

**Comment by jainkrati** [comment]
as per Mitch, gitcoin might be one of the reasons the values have changed

**Comment by jainkrati** [comment]
meriem to investigate further

**Comment by Meriem-BM** [comment]
@CarlosQ96, @RamRamez  after reviewing both the BE and FE code, I believe there might be a potential issue. It could be that if the 'refreshUserScores' query fails to update the user record (even though it still returns the updated user record), there could be a problem. Specifically, if this failure happens while the user is signing in (connecting to their wallet or passport), the score may not get saved due to the failure of the update method. Consequently, when the user visits the /passport page, the score displayed is the old one fetched from the database, not the updated score.

I'm still uncertain about this, but perhaps we could delve into the logs (if you have) to see if there are any records indicating failures related to the 'refreshUserScores' query.

For now I will test on staging and see if I can fall into this case.

**Comment by CarlosQ96** [comment]
@laurenluz still not sure what is the solution here. Wait for them to implement the notifications? force refresh user scores constantly? 

I dont think its a bug, its a matter of deciding what to do. @jainkrati @maryjaf 

As we know passports expire in 3 month. Most people went back to 0.  @RamRamez what do you think?

**Comment by RamRamez** [comment]
@CarlosQ96 the main issue that @laurenluz is concerned is NOT about "passports expire in 3 month". Also Lauren doesn't want auto refresh

If auto refresh fixes this problem, it's ok, but the main issue is that, the banner in UI says you are eligible but donations had not been counted as eligible and score was saved as zero in DB

Jake and Griff had this issue with their donations

**Comment by laurenluz** [comment]
@Meriem-BM the reason we do the "fillQfRoundDonationsUserScores" after the round has ended is because ... if the user updates their passport score near the end of the round to above the threshold... as long as they do it before the round ends... their earlier donations (made before their score was above the threshold) should count for QF.

So we want the latest passport score... and it should ideally also be the highest passport score that happened during the round.

**Comment by Meriem-BM** [comment]
> @Meriem-BM the reason we do the "fillQfRoundDonationsUserScores" after the round has ended is because ... if the user updates their passport score near the end of the round to above the threshold... as long as they do it before the round ends... their earlier donations (made before their score was above the threshold) should count for QF.
> 
> So we want the latest passport score... and it should ideally also be the highest passport score that happened during the round.

Got it, it actually updates it only for donation with empty score, so not every donation, Thanks

**Comment by Meriem-BM** [comment]
@RamRamez, I found a potential issue in the FE behavior. When we refresh the passport score, it does not get updated in the global store (user state). As a result, when the user navigates through the app, they continue to see the initial data loaded in the store until they refresh the page. We need to ensure the global store is updated after certain events, like refreshing the score, so the user always sees the latest data without needing to refresh the page.

**Comment by Meriem-BM** [comment]
https://github.com/user-attachments/assets/983f5929-4986-4b78-9db1-3c35512776d3

**Comment by divine-comedian** [comment]
@laurenluz @RamRamez is this issue in QA or is it completed?

**Comment by laurenluz** [comment]
@Meriem-BM @RamRamez - can you update?

**Comment by RamRamez** [comment]
I tested the scenario that @Meriem-BM showed but I couldn't reproduce. Also I tested the scenario that Griff and Jake had problem before and I couldn't find any inconsistency between projects page and my account page in showing passport state.
/passport page has been removed and now we show eligibility in my account, I checked the codes and we fetch passport score for both projects page and my account from `usePassport` component, so it's not possible that they are inconsistent.
I believe we can mark this issue as resolved unless we can reproduce the issue.
