### ISSUE TITLE
Create new "unique donor" variable corresponding to each QF round for the archived qf round page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4245]
related to #3748 

On the archived QF round page, we are showing "unique donors" as a number of unique addresses that donated in the round.

Would like to hear your feedback @koday1 on if you think we should improve this number to behave as follows:

1. Add a setting in admin bro where and admin can mark if a round is completed or not. If the round is not completed, the "unique donors" on the archived qf round says "pending". If the round is completed...

2. "Unique donors" is a new variable stored in our backend calculated by:
- considering the total number of unique addresses that donated to qf projects during active round
- exclude donors whose passport score was below the "threshold"
- exclude donors who were "flagged as sybil" for the round

This would require us doing some extra development work, but I think then would display the number that I consider as "unique donors". We also may want to consider if we should include donors whose donations to a single project were less than the minUSDvalue... I think they should be included because they are unique still...

**Comment by Meriem-BM** [comment]
@laurenluz, regarding the `completed` field you requested to add to adminBro, could you clarify its purpose? We already have a field called `isActive`. Is it the same thing, or is it different? If so, could you please explain?

cc: @CarlosQ96

**Comment by Meriem-BM** [comment]
@ca

> @laurenluz, regarding the `completed` field you requested to add to adminBro, could you clarify its purpose? We already have a field called `isActive`. Is it the same thing, or is it different? If so, could you please explain?
> 
> cc: @CarlosQ96

@CarlosQ96 explained, thanks guys

**Comment by Meriem-BM** [comment]
Hey @maryjaf this issue is ready for test

**Comment by maryjaf** [comment]
I have one question, could you please check @CarlosQ96 @Meriem-BM 

How long after the date of the "End date" field in the admin panel for a round, the data analysis (for example, donors less than one dollar, donors with low score, etc.) is done?
This analysis is systematic, right?

**Comment by Meriem-BM** [comment]
> I have some questions, could you please check @CarlosQ96 @Meriem-BM
> 
> 1- How long after the date of the "End date" field in the admin panel for a round, the data analysis (for example, donors less than one dollar, donors with low score, etc.) is done? This analysis is systematic, right?
> 
> 2- In the page of round https://staging.giveth.io/qf-archive/6 the "Donations" is shown $0.04 but in the list of archived donations it is shown "$3.01" What is the difference between these fields ? it isn't exactly related to this issue but I should know about it for testing the logic of its calculation
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/338877465-ce21e42b-8a68-482c-bf60-5e573e0cf538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODU2NTEsIm5iZiI6MTcxODE4NTM1MSwicGF0aCI6Ii8xMTE1MjkxODUvMzM4ODc3NDY1LWNlMjFlNDJiLThhNjgtNDgyYy1iZjYwLTVlNTczZTBjZjUzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwOTQyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmViZDA4ZDBmZGRlY2FjOWQwM2YyMjQwNjE1Yjg2NDZhN2JhNDViZjEyNDUzZTQxNzlhOGM5N2IwYzM1MDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FxCim30rYf88A-YGMPSEbyP_Vaw_O92KG8IhnfUChgs) ![image](https://private-user-images.githubusercontent.com/111529185/338880835-09309960-74bd-4c49-93db-7c1b534b964c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODU2NTEsIm5iZiI6MTcxODE4NTM1MSwicGF0aCI6Ii8xMTE1MjkxODUvMzM4ODgwODM1LTA5MzA5OTYwLTc0YmQtNGM0OS05M2RiLTdjMWI1MzRiOTY0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwOTQyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTcxZjlkNjBhMTQ0MmVlMmRmNGNlZWVhMTQ3YzVhOWQxYjA1M2E1ZmZhNzM0YWE3ODhiNzcwOWE1NDg0MDAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uKKNJcl8D81ILbkPqbg-9mxZFo2LDxutRqpbTlTdplU)

For the first point I think @laurenluz can provide a better answer.
For the 2nd point, you're right, I'm working on it, seems like the query is missing a condition, and also it retrieves the amount not USD value, I'll fix that.

**Comment by Meriem-BM** [comment]
> I have some questions, could you please check @CarlosQ96 @Meriem-BM
> 
> 1- How long after the date of the "End date" field in the admin panel for a round, the data analysis (for example, donors less than one dollar, donors with low score, etc.) is done? This analysis is systematic, right?
> 
> 2- In the page of round https://staging.giveth.io/qf-archive/6 the "Donations" is shown $0.04 but in the list of archived donations it is shown "$3.01" What is the difference between these fields ? it isn't exactly related to this issue but I should know about it for testing the logic of its calculation
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/338877465-ce21e42b-8a68-482c-bf60-5e573e0cf538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDUzOTcsIm5iZiI6MTcxODcwNTA5NywicGF0aCI6Ii8xMTE1MjkxODUvMzM4ODc3NDY1LWNlMjFlNDJiLThhNjgtNDgyYy1iZjYwLTVlNTczZTBjZjUzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMDA0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWQ2NDExN2FkMGM2YmU1NWY5Njc2ZGU2M2YyMWE1NDYzODQ0OWNkZDIyMjAyNjFiOTYxMzBiNGQ1YzI3M2QxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q5KXBr426MdV8gOLuxFtBgwvZsAE69zu5Jm6K1UWL-E) ![image](https://private-user-images.githubusercontent.com/111529185/338880835-09309960-74bd-4c49-93db-7c1b534b964c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDUzOTcsIm5iZiI6MTcxODcwNTA5NywicGF0aCI6Ii8xMTE1MjkxODUvMzM4ODgwODM1LTA5MzA5OTYwLTc0YmQtNGM0OS05M2RiLTdjMWI1MzRiOTY0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMDA0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTUwMjQ5M2U4ZTljNDgyZmQyZDc1NzQ3NWEyN2EzZWMzNzViZWQ2Zjc0ZTIwNWE0NDhhNTFiOTE1ZGYwOTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9-sRDVK9-jAyYaU68eRzhAvj3fJ7NvoEObQkDOGNhVA)

Hey @maryjaf, I fixed the 2nd issue here.

**Comment by Meriem-BM** [comment]
For the 1st point I think the admin set it manually on adminJS once data analysis are done, from what @laurenluz mentioned here 

> related to #3748
> 
> On the archived QF round page, we are showing "unique donors" as a number of unique addresses that donated in the round.
> 
> Would like to hear your feedback @koday1 on if you think we should improve this number to behave as follows:
> 
> 1. Add a setting in admin bro where and admin can mark if a round is completed or not. If the round is not completed, the "unique donors" on the archived qf round says "pending". If the round is completed...
> 2. "Unique donors" is a new variable stored in our backend calculated by:
> 
> * considering the total number of unique addresses that donated to qf projects during active round
> * exclude donors whose passport score was below the "threshold"
> * exclude donors who were "flagged as sybil" for the round
> 
> This would require us doing some extra development work, but I think then would display the number that I consider as "unique donors". We also may want to consider if we should include donors whose donations to a single project were less than the minUSDvalue... I think they should be included because they are unique still...

**Comment by maryjaf** [comment]
> 2- In the page of round https://staging.giveth.io/qf-archive/6 the "Donations" is shown $0.04 but in the list of archived donations it is shown "$3.01"
> What is the difference between these fields ?
> it isn't exactly related to this issue but I should know about it for testing the logic of its calculation

I still see different numbers in the list of archived QF rounds and the page of a archive qf 
could you please check again @Meriem-BM  
List:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b8255793-8226-46e2-87a0-5b8bc94e72c4)
QF page :
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ebc57407-ae2b-4882-9d84-06a4ead94161)

**Comment by maryjaf** [comment]
I'm not sure maybe this problem is also related to problem of discrepancy in total donation and...  that @RamRamez is working on it

**Comment by Meriem-BM** [comment]
> I'm not sure maybe this problem is also related to problem of discrepancy in total donation and... that @RamRamez is working on it

Yes @maryjaf, @RamRamez made a change into the query that get donations value on 2nd screen.

**Comment by RamRamez** [comment]
> > 2- In the page of round https://staging.giveth.io/qf-archive/6 the "Donations" is shown $0.04 but in the list of archived donations it is shown "$3.01"
> > What is the difference between these fields ?
> > it isn't exactly related to this issue but I should know about it for testing the logic of its calculation
> 
> I still see different numbers in the list of archived QF rounds and the page of a archive qf could you please check again @Meriem-BM List: ![image](https://private-user-images.githubusercontent.com/111529185/340650382-b8255793-8226-46e2-87a0-5b8bc94e72c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NDMzNjMsIm5iZiI6MTcxODc0MzA2MywicGF0aCI6Ii8xMTE1MjkxODUvMzQwNjUwMzgyLWI4MjU1NzkzLTgyMjYtNDZlMi04N2EwLTViOGJjOTRlNzJjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQyMDM3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGExMTU4N2FkZDc0YjU1YjMxZmI2NTU0MDY5MTgxMjcyOTczMzc5YmM5YTY0ODhlODc1ZTVhNTQ1YzMzOGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P7oBjRzDSJMqJtsHsfkEpxusIVnx8MgxMQeiHn-XMG4) QF page : ![image](https://private-user-images.githubusercontent.com/111529185/340650458-ebc57407-ae2b-4882-9d84-06a4ead94161.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NDMzNjMsIm5iZiI6MTcxODc0MzA2MywicGF0aCI6Ii8xMTE1MjkxODUvMzQwNjUwNDU4LWViYzU3NDA3LWFlMmItNDg4Mi05ZDg0LTA2YTRlYWQ5NDE2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQyMDM3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYThhMzFhYjMyZTA4Mzc2Y2I4N2Y2MTQwMzgzNGQwNzY2NTVmOTZmNmY5NTAyMjRlNmY0ODNkZTU0ZTEzYWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ROZTrmK3mZQwV15TJdTXMFsjmxamILEhOHChIvrmc6w)

@maryjaf This is fixed, please test again

**Comment by maryjaf** [comment]
> I still see different numbers in the list of archived QF rounds and the page of a archive qf

This problem has been resolved.
but there is some problem that I can't complete the test of this issue and other QF issue, despite these problems, the tests are not reliable 

in below pic:
- There is a donation in "round for test donor"
- but "Be the first to give" is shown in this tab and there is no estimated matching
- in project detail the estimated matching and "Donate first and lead the way" is shown !

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e1a57124-ee56-44bf-ad40-9b6c1fed4e01)

**Comment by Meriem-BM** [comment]
> > I still see different numbers in the list of archived QF rounds and the page of a archive qf
> 
> This problem has been resolved. but there is some problem that I can't complete the test of this issue and other QF issue, despite these problems, the tests are not reliable
> 
> in below pic:
> 
> * There is a donation in "round for test donor"
> * but "Be the first to give" is shown in this tab and there is no estimated matching
> * in project detail the estimated matching and "Donate first and lead the way" is shown !
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/340972270-e1a57124-ee56-44bf-ad40-9b6c1fed4e01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTU5ODEsIm5iZiI6MTcxODc5NTY4MSwicGF0aCI6Ii8xMTE1MjkxODUvMzQwOTcyMjcwLWUxYTU3MTI0LWVlNTYtNDRiZi1hZDQwLTliNmMxZmVkNGUwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxMTE0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjdjZjI2NjZmZmEwY2JiOTZlZTZiYjliNWZiMTc4ZGU4ZjI4YzcwM2FkN2M0M2M3NDEwYTk4ZGRmM2M5ZjQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zts9XCs_uKDbXpEQ5_ytS6U31yxeWji1HY9ZXJGeqeQ)

@Ramin I think the reason is that that donation doesn't meet min passport condition so it was excluded from the count, I don't know if we should apply this condition on active QF rounds 

```ts
export async function getProjectQfRoundStats(params: {
  projectId: number;
  qfRound: QfRound;
}): Promise<{ uniqueDonorsCount: number; sumValueUsd: number }> {
  const { projectId, qfRound } = params;
  const { minimumPassportScore, id: qfRoundId, beginDate, endDate } = qfRound;
  const result = await Donation.createQueryBuilder('donation')
    .select('COUNT(DISTINCT donation.userId)', 'uniqueDonors')
    .addSelect('SUM(donation.valueUsd)', 'totalDonationValueUsd')
    .leftJoin('donation.user', 'user')
    .where('donation.qfRoundId = :qfRoundId', { qfRoundId })
    .andWhere('donation.projectId = :projectId', { projectId })
    .andWhere('donation.status = :status', { status: 'verified' })
    .andWhere('user.passportScore >= :minimumScore', {
      minimumScore: minimumPassportScore,
    })
    .andWhere('donation.createdAt BETWEEN :beginDate AND :endDate', {
      beginDate,
      endDate,
    })
    .getRawOne();

  return {
    uniqueDonorsCount: parseInt(result.uniqueDonors, 10) || 0,
    sumValueUsd: parseFloat(result.totalDonationValueUsd) || 0,
  };
}
```

**Comment by RamRamez** [comment]
> > I still see different numbers in the list of archived QF rounds and the page of a archive qf
> 
> This problem has been resolved. but there is some problem that I can't complete the test of this issue and other QF issue, despite these problems, the tests are not reliable
> 
> in below pic:
> 
> * There is a donation in "round for test donor"
> * but "Be the first to give" is shown in this tab and there is no estimated matching
> * in project detail the estimated matching and "Donate first and lead the way" is shown !
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/340972270-e1a57124-ee56-44bf-ad40-9b6c1fed4e01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTM0MzIsIm5iZiI6MTcxODc5MzEzMiwicGF0aCI6Ii8xMTE1MjkxODUvMzQwOTcyMjcwLWUxYTU3MTI0LWVlNTYtNDRiZi1hZDQwLTliNmMxZmVkNGUwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxMDMyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmQ3M2U4YTBhMDYyODJjMWY3YjYwY2Y4NWM3YzhhNGE3YTAwMWViMTk4Mjk3ODlkYzYzNzI1NThkOTZkYzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rUCZcpwin0iD-O70q1CPRZNLvqEXYt4pnd731RVw66M)

@maryjaf I removed passport score condition. Please test again.

**Comment by maryjaf** [comment]
I think there is some problem in calculating number of donor,  when we expect this number be calculated after considering condition of donors

- In this round there are 3 unique donors 
   https://staging.giveth.io/qf-archive/MJ%20test%20round
- The round is over
- I Tap on "Update Qf Round Histories" in QF round history in admin panel
- and I've checked the box: "Is Data Analysis Done"
- I expect that the real number of unique donor be decreased in the list of archived QF but it is shown 3 
https://staging.giveth.io/qf-archive
(since one of this donors is "0x958e6AaaCfDea802D70e86d820259F0a970BA6a8" and there is a project whit this recipent address in this  round  and based on condition, this donor shouldn't be calculated )


![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/58b09a20-67ff-4e6b-9b9e-a227ed94e289)

cc:  @mohammadranjbarz  @Meriem-BM @laurenluz

**Comment by Meriem-BM** [comment]
> I think there is some problem in calculating number of donor, when we expect this number be calculated after considering condition of donors
> 
> * In this round there are 3 unique donors
>   https://staging.giveth.io/qf-archive/MJ%20test%20round
> * The round is over
> * I Tap on "Update Qf Round Histories" in QF round history in admin panel
> * and I've checked the box: "Is Data Analysis Done"
> * I expect that the real number of unique donor be decreased in the list of archived QF but it is shown 3
>   https://staging.giveth.io/qf-archive
>   (since one of this donors is "0x958e6AaaCfDea802D70e86d820259F0a970BA6a8" and there is a project whit this recipent address in this  round  and based on condition, this donor shouldn't be calculated )
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/341339925-58b09a20-67ff-4e6b-9b9e-a227ed94e289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQzMzAsIm5iZiI6MTcxODg3NDAzMCwicGF0aCI6Ii8xMTE1MjkxODUvMzQxMzM5OTI1LTU4YjA5YTIwLTY3ZmYtNGU2Yi05YjllLWEyMjdlZDk0ZTI4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwOTAwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNThjOTkwZDUzMWRmYWFiY2E5Y2JmZDcyMDZlMDg2YTQ0YTI0NWEwYTI2MjMxMWQwYTA0YjMzOTllNTlmMDgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O9bpdIt01KDPCGHULh-nEpuNhm_eiFFe_UuioEh7xDs)
> 
> cc: @mohammadranjbarz @Meriem-BM @laurenluz

@maryjaf I think that donor fulfill the condition (he is not flagged as sybil & his passport score is greater than the minimum of this QF round), let me know what condition you meant.

**Comment by maryjaf** [comment]
> > I think there is some problem in calculating number of donor, when we expect this number be calculated after considering condition of donors
> > 
> > * In this round there are 3 unique donors
> >   https://staging.giveth.io/qf-archive/MJ%20test%20round
> > * The round is over
> > * I Tap on "Update Qf Round Histories" in QF round history in admin panel
> > * and I've checked the box: "Is Data Analysis Done"
> > * I expect that the real number of unique donor be decreased in the list of archived QF but it is shown 3
> >   https://staging.giveth.io/qf-archive
> >   (since one of this donors is "0x958e6AaaCfDea802D70e86d820259F0a970BA6a8" and there is a project whit this recipent address in this  round  and based on condition, this donor shouldn't be calculated )
> > 
> > ![image](https://private-user-images.githubusercontent.com/111529185/341339925-58b09a20-67ff-4e6b-9b9e-a227ed94e289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQzMzAsIm5iZiI6MTcxODg3NDAzMCwicGF0aCI6Ii8xMTE1MjkxODUvMzQxMzM5OTI1LTU4YjA5YTIwLTY3ZmYtNGU2Yi05YjllLWEyMjdlZDk0ZTI4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwOTAwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNThjOTkwZDUzMWRmYWFiY2E5Y2JmZDcyMDZlMDg2YTQ0YTI0NWEwYTI2MjMxMWQwYTA0YjMzOTllNTlmMDgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O9bpdIt01KDPCGHULh-nEpuNhm_eiFFe_UuioEh7xDs)
> > cc: @mohammadranjbarz @Meriem-BM @laurenluz
> 
> @maryjaf I think that donor fulfill the condition (he is not flagged as sybil & his passport score is greater than the minimum of this QF round), let me know what condition you meant.

only these two conditions should be considered in calculation of unique donor?
-exclude donors whose passport score was below the "threshold"
-exclude donors who were "flagged as sybil" for the round

there are some other conditions for estimated matching that I thought all of them is considered also for unique donor

**Comment by maryjaf** [comment]
> -exclude donors whose passport score was below the "threshold"
> -exclude donors who were "flagged as sybil" for the round

 based on these 2 conditions, the number of donor of below round should be set: 0 
 https://staging.giveth.io/qf-archive/round%20for%20test%20donor
 
-one of them had low score : 0x523E41A134Ab0999F2dC844eA02d9b53cC28fD1a
- this address has been added as a sybil address in this round (https://impact-graph.serve.giveth.io/admin/resources/Sybil/records/30/show)


![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2918e270-1743-4445-9790-ed12d190a263)

**Comment by Meriem-BM** [comment]
> > -exclude donors whose passport score was below the "threshold"
> > -exclude donors who were "flagged as sybil" for the round
> 
> based on these 2 conditions, the number of donor of below round should be set: 0 https://staging.giveth.io/qf-archive/round%20for%20test%20donor
> 
> * one of them had low score : 0x523E41A134Ab0999F2dC844eA02d9b53cC28fD1a
> * this address has been added as a sybil address in this round (https://impact-graph.serve.giveth.io/admin/resources/Sybil/records/30/show)
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/341375943-2918e270-1743-4445-9790-ed12d190a263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4ODE1MjIsIm5iZiI6MTcxODg4MTIyMiwicGF0aCI6Ii8xMTE1MjkxODUvMzQxMzc1OTQzLTI5MThlMjcwLTE3NDMtNDQ0NS05NzkwLWVkMTJkMTkwYTI2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxMTAwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjQxYmY0NzQyN2EwYzVkYzNiNTAwMzYxZGQ4NGU2MWFkNGE4MWIwMGY5YmJhYjFmYmRmOWJhMmMzZDc1ZjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8dB_XSAfkzU6IP0973w3HFudMxSumKsX85gNYCPr9Mo)

You're right here, 2nd one was added as sybil, but when I checked the user https://impact-graph.serve.giveth.io/admin/resources/User/records/419/show isKnownAsSybil must change to `Yes` but it still `No`, I will check why.

**Comment by Meriem-BM** [comment]
Hey @maryjaf can you test this again.

**Comment by maryjaf** [comment]
> based on these 2 conditions, the number of donor of below round should be set: 0
> https://staging.giveth.io/qf-archive/round%20for%20test%20donor

Thanks @Meriem-BM I tested yesterday and this item. has been fixed, but I should do more test and it seems the change isn't on staging, could you please check?

**Comment by Meriem-BM** [comment]
> > based on these 2 conditions, the number of donor of below round should be set: 0
> 
> > https://staging.giveth.io/qf-archive/round%20for%20test%20donor
> 
> 
> 
> Thanks @Meriem-BM I tested yesterday and this item. has been fixed, but I should do more test and it seems the change isn't on staging, could you please check?

You mean on production?

**Comment by maryjaf** [comment]
> > > based on these 2 conditions, the number of donor of below round should be set: 0
> > 
> > 
> > > https://staging.giveth.io/qf-archive/round%20for%20test%20donor
> > 
> > 
> > Thanks @Meriem-BM I tested yesterday and this item. has been fixed, but I should do more test and it seems the change isn't on staging, could you please check?
> 
> You mean on production?

Staging

**Comment by maryjaf** [comment]
Let me know, when it's merged on staging again

**Comment by Meriem-BM** [comment]
> Let me know, when it's merged on staging again

Yes @maryjaf, it's merged now

**Comment by maryjaf** [comment]
In this round ["donor test round"](https://impact-graph.serve.giveth.io/admin/resources/QfRound/records/110/show) there are 4 donation with 3 unique donor 

- 0xa1179f64638adb613ddaac32d918eb6beb824104 : eligible 
score more than 1 , donation more than :0.0001

- 0xa602bba404f3eea8231398df0cfa78b46550331d : not eligible
score:0 

- 0xcd192b61a8Dd586A97592555c1f5709e032F2505:  not eligible
[project fraud](https://impact-graph.serve.giveth.io/admin/resources/ProjectFraud/records/8/show)

I expected number of unique donor be shown 1 but it is 0 , could you please check this ? @Meriem-BM 
https://staging.giveth.io/qf-archive

I have one hypothesis maybe the reason of this behavior is that I set 0xa1179f64638adb613ddaac32d918eb6beb824104 as a sybil adrress for another round but not for ["donor test round"](https://impact-graph.serve.giveth.io/admin/resources/QfRound/records/110/show) round , in this case for the "donor test round" round this address shouldn't be counted as a sybil address
@Meriem-BM

**Comment by Meriem-BM** [comment]
Thanks for catching that @maryjaf, I updated the query to handle these case, here is what is **excluded** when calculating unique donors:

- Keeping only **unique** donors that donated during that QF round **period**
- Donations with wallet address **marked as sybil** for that QF round
- User passport score **less** than the minimum passport score for that QF round
- Donations that are not `verified`
- Donations for projects marked as fraud for that QF round

**Comment by maryjaf** [comment]
> Thanks for catching that @maryjaf, I updated the query to handle those cases, here is what is **excluded** when calculating unique donors:
> 
> * Keeping only **unique** donors that donated during that QF round **period**
> * Donations with wallet address **marked as sybil** for that QF round
> * User passport score **less** than the minimum passport score for that QF round
> * Donations that are not `verified`
> * Donations to projects marked as fraud for that QF round



> * Add a setting in admin bro where and admin can mark if a round is completed or not. If the round is not completed, the "unique donors" on the archived qf round says "pending". If the round is completed...
> * "Unique donors" is a new variable stored in our backend calculated by:

Thanks @Meriem-BM 
Now based on these conditions the showing number of unique donor is correct
