### ISSUE TITLE
Stellar| two different stellar donation to one project

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4592]
**Describe the bug**

- I create one 0.01 donation to test stellar project 
- donation status is waiting in donation page 
- and in receipt page, transaction id:900, the status is pending as expected 
- after a few mins I create a new 0.01 donation  to test stellar project
- donation status is waiting in donation page and transaction id 901 is pending as expected 
- after a while I see the below screen record 
- the transactionid:900 is shown failed but the timer is counting in receipt page  ! but in donation page of this transaction the status is pending and the timer is shown based on the time of second transaction 

https://github.com/user-attachments/assets/a51eeaaf-16bf-4cda-9f34-8228063fa253

**Expected behavior**
What is the expected result in this scenario?
by creating new donation if the status of the first transaction is pending should be changed to faild?
or user could be able to do concurrent  donation to a project? @MoeNick

**Comment by MoeNick** [comment]
As far as I remember yesterday we decided not to let the user create another transaction by showing them the QR timer page with a toast message. `You already have another pending donation, please donate or click back to create another one with a different amount.`
@Meriem-BM @maryjaf

**Comment by maryjaf** [comment]
-  please take a look on below screen record to see a new behavior @MoeNick 

- [ ] By tapping on back the warning message remains in donation page 
- [ ] By tapping on back, I expect the previous donation be changed into failed in receipt page, but only by refreshing I could see failed status, is this accepted?

https://github.com/user-attachments/assets/bafd5a09-c417-4186-b022-4ab7c18964ab

**Comment by Meriem-BM** [comment]
> * please take a look on below screen record to see the new behavior @MoeNick
> * [ ]  1- By tapping on back the warning message remains in donation page
> * [ ]  2- By tapping on back, I expect the previous donation be changed into failed in receipt page, but only by refreshing I could see failed status, is this accepted?
> 
>  Screen.Recording.2024-08-22.at.10.31.07.AM.mov 
> @Meriem-BM

Can you recheck this @maryjaf

**Comment by maryjaf** [comment]
I've forgotten update the status of these 2 problems, they have been resolved , Thanks @Meriem-BM 
but could you please take a look on below screen record

- I have on open donation page and the check donation page(receipt) is open 
- I create second donation 
- the warning message is shown correctly 
- by tapping on back icon, the status is changed into failed in receipt page 
- but in first donation page I see the status is still pending 


https://github.com/user-attachments/assets/0fb4eedf-1938-4e1e-a5c1-d905000ba5fe

**Comment by Meriem-BM** [comment]
> I've forgotten update the status of these 2 problems, they have been resolved , Thanks @Meriem-BM but could you please take a look on below screen record
> 
> * I have on open donation page and the check donation page(receipt) is open
> * I create second donation
> * the warning message is shown correctly
> * by tapping on back icon, the status is changed into failed in receipt page
> * but in first donation page I see the status is still pending
> 
>  Screen.Recording.2024-08-27.at.4.11.23.PM.mov 
> cc: @MoeNick

@maryjaf you have two open pages on same donation, it's possible if we want to update, just for now we need to solve the problem with the Event that's it's still not working on staging.

**Comment by maryjaf** [comment]
> > I've forgotten update the status of these 2 problems, they have been resolved , Thanks @Meriem-BM but could you please take a look on below screen record
> > 
> > * I have on open donation page and the check donation page(receipt) is open
> > * I create second donation
> > * the warning message is shown correctly
> > * by tapping on back icon, the status is changed into failed in receipt page
> > * but in first donation page I see the status is still pending
> > 
> > Screen.Recording.2024-08-27.at.4.11.23.PM.mov
> > cc: @MoeNick
> 
> @maryjaf you have two open pages on same donation, it's possible if we want to update, just for now we need to solve the problem with the Event that's it's still not working on staging.

I'll recheck it after fixing the problem related to event

**Comment by maryjaf** [comment]
> I've forgotten update the status of these 2 problems, they have been resolved , Thanks @Meriem-BM but could you please take a look on below screen record
> 
> * I have on open donation page and the check donation page(receipt) is open
> * I create second donation
> * the warning message is shown correctly
> * by tapping on back icon, the status is changed into failed in receipt page
> * but in first donation page I see the status is still pending
> 
>  Screen.Recording.2024-08-27.at.4.11.23.PM.mov 
> cc: @MoeNick

The problem relate to this "* but in first donation page I see the status is still pending", has been fixed and now the failed status is shown correctly in this scenario
but there is a problem related to the timer, the timer isn't stopped 

@Meriem-BM 

https://github.com/user-attachments/assets/1c5aa730-5e29-41eb-a030-b9cb8daa44df

**Comment by maryjaf** [comment]
> > I've forgotten update the status of these 2 problems, they have been resolved , Thanks [@Meriem-BM](https://github.com/Meriem-BM) but could you please take a look on below screen record
> > 
> > * I have on open donation page and the check donation page(receipt) is open
> > * I create second donation
> > * the warning message is shown correctly
> > * by tapping on back icon, the status is changed into failed in receipt page
> > * but in first donation page I see the status is still pending
> > 
> > Screen.Recording.2024-08-27.at.4.11.23.PM.mov
> > cc: [@MoeNick](https://github.com/MoeNick)
> 
> The problem relate to this "* but in first donation page I see the status is still pending", has been fixed and now the failed status is shown correctly in this scenario but there is a problem related to the timer, the timer isn't stopped
> 
> [@Meriem-BM](https://github.com/Meriem-BM)
> 
>  Screen.Recording.2024-08-29.at.2.21.53.PM.mov

This problem hasn't been fixed @Meriem-BM

**Comment by maryjaf** [comment]
> * I have on open donation page and the check donation page(receipt) is open
> * I create second donation
> * the warning message is shown correctly
> * by tapping on back icon, the status is changed into failed in receipt page
> * but in first donation page I see the status is still pending

new behavior of this  scenario is like below screen record

 I have on open donation page and the check donation page(receipt) is open
 I create second donation
 the warning message is shown correctly
 by tapping on back icon, the status is changed into failed in receipt page
 and in first donation page the status is shown pending and the timer stops 

Is it accepted or the timer should be shown 0 ? @MoeNick 
if it is fine we can call this issue DONE

https://github.com/user-attachments/assets/656b8792-1c45-40c1-b4da-33b6809c7754

**Comment by MoeNick** [comment]
Sorry I could not load the video yet :(

**Comment by maryjaf** [comment]
This is what happens @MoeNick 

> by tapping on back icon, the status is changed into failed in receipt page
> and in first donation page the status is shown failed and **the timer stops** (for example in this case the timer stops on 12:11 )
> Is it accepted or the timer should be shown 0 ? @MoeNick

![image](https://github.com/user-attachments/assets/325b725a-41e5-42dc-8ec5-bf5d9092ea78)
