### ISSUE TITLE
Users unable to access the All Projects page on staging, throwing internal server error

### ISSUE THREAD

**Issue by LatifatAbdullahi** [Giveth/giveth-dapps-v2#4797]
![image](https://github.com/user-attachments/assets/d782a3e6-1a14-438a-bf64-93d9c14254dd)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi looks like @CarlosQ96 rolled back some recent changes - it should be working now.

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @CarlosQ96 

 The issue is still reproducible

![image](https://github.com/user-attachments/assets/ed07821d-6ad4-46f2-aa1f-8ee9191a92af)

**Comment by divine-comedian** [comment]
appears to be fixed for now since carlos rolled back the latest changes from migrating mongoDB actions.

![image](https://github.com/user-attachments/assets/cd2c7067-7c8d-4d8a-8a55-72e8f7a3bd0c)

@LatifatAbdullahi if you experience this issue again please re-open the issue
