### ISSUE TITLE
Anonymous Donations should not be shown in the public profile page

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#574]
I tried donating GIV anonymously to this project and I can see this success page:
https://giveth-dapps-v2.vercel.app/donate/giveth-2021:-retreat-to-the-future

![image](https://user-images.githubusercontent.com/93360299/164250929-4643b8cc-7e5f-418d-a500-4751722ee6d8.png)

I'm just wondering if it's possible to indicate in the Success page that the donation was made anonymously. Or is it not really possible to donate anonymously as the transaction will still be recorded? This is the donation: https://blockscout.com/xdai/mainnet/tx/0xafb738af641604a7f13e77a70af5637bf5e75d57b0f6b797cfc2ff750c38da1e 

It's also displayed on my Account page:
![image](https://user-images.githubusercontent.com/93360299/164251492-25ebe567-32a3-4ed2-a9bc-04103c22b8fc.png)

I'm not sure about this but I still added it as an issue so you can check :) Thank you! 

@MoeNick

**Comment by missgene** [comment]
I also made an anonymous donation here: https://blockscout.com/xdai/mainnet/tx/0xcbb321bd772be2d4635d12c19748be3372f74acf6f6ff777646264b07241557d 

It's also shown on my profile:
![image](https://user-images.githubusercontent.com/93360299/164251966-ec94eb64-5993-4d30-a2f6-e03eeaa12fc1.png)

**Comment by MoeNick** [comment]
What about your public profile?

**Comment by missgene** [comment]
It's also there.. This is my public profile: 

https://giveth-dapps-v2.vercel.app/user/0xbE6f56Ed9E10E5F58876F7bDF1C83EeDaa721fbc

**Comment by CarlosQ96** [comment]
I'll check this.

**Comment by mohammadranjbarz** [comment]
@MoeNick
As for both public profile donations, and `My Donations` page we use one query `donationsByUserId` I think we should set a condition if a logged-in user call this query for getting his/her donations we return all donations, but if someone else wants to see donations of a user we exclude **anonymous** donations

**Comment by MoeNick** [comment]
Let's wait to finilize the flow first. it has some UI/UX impact.

**Comment by mohammadranjbarz** [comment]
@MoeNick 
It just fix this particular issue and you can test it in the way I explained in below comment
https://github.com/Giveth/impact-graph/pull/498#pullrequestreview-959996253

and about 
https://github.com/Giveth/giveth-dapps-v2/issues/638

we can decide and implement later

**Comment by divine-comedian** [comment]
Trying to test this issue on `staging.giveth.io`
clean cache and cookies
brave browser

I cannot seem to view user profiles while not logged in

![image](https://user-images.githubusercontent.com/67759413/169844945-70eeef38-9e20-4841-bb65-0cff6992be4a.png)

while logged in I try to view another user's profile and it only shows me my profile:

![image](https://user-images.githubusercontent.com/67759413/169845230-b12e2a5e-9513-472b-adaf-0d89f4a037f2.png)

this bug is preventing me from testing this issue. I tested on `giveth.io` and we do not have this issue.

**Comment by alireza-sharifpour** [comment]
I fixed the issue that @divine-comedian is experiencing related to User public profile view on staging
https://github.com/Giveth/giveth-dapps-v2/pull/781

**Comment by MoeNick** [comment]
Would u pls test it again @divine-comedian ?

**Comment by divine-comedian** [comment]
testing `staging.giveth.io`
clean cache and cookies 
brave browser

this issue still seems to be partially resolved - while donating anonymously I receive no confirmation that it was anonmyous on the success page.

![image](https://user-images.githubusercontent.com/67759413/170073536-90ecf642-f078-453a-8764-a6282b27f859.png)


on my public and private profile while logged in w/ the same user I can see my anonymous donations. 

![image](https://user-images.githubusercontent.com/67759413/170074456-1dfed903-1e36-4290-8ce5-aa2c505e1638.png)


however even while connected to a different account i can no longer see those donations on the other account. 

![image](https://user-images.githubusercontent.com/67759413/170074363-a1b687a2-2b13-42f2-9de0-df86b62c37f1.png)

@MoeNick  not sure if this is a front-end or back-end issue to fix the final requested change

**Comment by mohammadranjbarz** [comment]
@MoeNick  @divine-comedian 
I think it's exactly what we wanted, a user should see his anonymous donations, but other users should not see the other person's anonymous donations

**Comment by mohammadranjbarz** [comment]
@MoeNick  @divine-comedian 
And this one
> this issue still seems to be partially resolved - while donating anonymously I receive no confirmation that it was anonmyous on the success page.
I guess it's related to frontend ( @RamRamez , @MohammadPCh )

**Comment by RamRamez** [comment]
> testing `staging.giveth.io` clean cache and cookies brave browser
> 
> this issue still seems to be partially resolved - while donating anonymously I receive no confirmation that it was anonmyous on the success page.
> 
> ![image](https://user-images.githubusercontent.com/67759413/170073536-90ecf642-f078-453a-8764-a6282b27f859.png)
> 
> on my public and private profile while logged in w/ the same user I can see my anonymous donations.
> 
> ![image](https://user-images.githubusercontent.com/67759413/170074456-1dfed903-1e36-4290-8ce5-aa2c505e1638.png)
> 
> however even while connected to a different account i can no longer see those donations on the other account.
> 
> ![image](https://user-images.githubusercontent.com/67759413/170074363-a1b687a2-2b13-42f2-9de0-df86b62c37f1.png)
> 
> @MoeNick not sure if this is a front-end or back-end issue to fix the final requested change

@MoeNick

**Comment by jeevanplus007** [comment]
@mohammadranjbarz  Kindly have a look

**Comment by mohammadranjbarz** [comment]
> @MoeNick @divine-comedian I think it's exactly what we wanted, a user should see his anonymous donations, but other users should not see the other person's anonymous donations

@jeevanplus007  I think we should wait for @MoeNick  to back to work, then we can discuss about it

**Comment by MoeNick** [comment]
I'm available in 2 hours, we need to talk?

**Comment by divine-comedian** [comment]
my only comment was that there is no confirmation that the donation was made anonymously on the hi 5 page but perhaps that is out of scope of this issue. willing to call it good enough to be DONE

**Comment by maryjaf** [comment]
Can we move this issue to Done? @divine-comedian
