### ISSUE TITLE
GIVpower - Single Project View - Boosting Modal

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#761]
- No GIVpower modal -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12568%3A236170)

- Boosting modal -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12568%3A232403)

- Confirmation modal -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12568%3A236144)

- First time boosting.

**Comment by MoeNick** [comment]
Should we remove Unallocated GIVpower @mosaeedi ?
Copy on toast for first time boosting.

**Comment by MoeNick** [comment]
@divine-comedian @maryjaf pls confirm and merge.

**Comment by divine-comedian** [comment]
In this view here- when a project has not been boosted yet the copy seems a bit off.

This is not my project so it should not refer to this as 'your project' copy should be:

'This project hasn't received any boosts yet!'
'Share this project on social media and ask your friends for a boost!'

- it would be cool if 'Share this project' opened the modal similar to the share button on the card on the right under the donate button.

![image](https://user-images.githubusercontent.com/67759413/190466210-f4784d4d-00e3-4cfe-b520-df505d9f6d59.png)

**Comment by divine-comedian** [comment]
this project has no boosts but it is rank `#8`, how can it have a ranking with no GIVpower? 

![image](https://user-images.githubusercontent.com/67759413/190470727-245017d2-b395-41d3-a8f8-e1f9b8e55d58.png)

**Comment by maryjaf** [comment]
Please check this scenario:
I'm on a GIVpower tab of a project
I select BOOST and complete the process
I expect that the boosting list will be updated at the end of the process
But this does not happen and I have to refresh the page to see the changes

And one more thing, when a project is boosted by several users, The TOTAL GIVPOWER & PROJECT RANK is displayed as pic below:
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/29854959-5bc0-4caa-82ff-5255bba00c4e)

**Comment by aminlatifi** [comment]
> this project has no boosts but it is rank `#8`, how can it have a ranking with no GIVpower?
> 
> ![image](https://user-images.githubusercontent.com/67759413/190470727-245017d2-b395-41d3-a8f8-e1f9b8e55d58.png)

It had rank #8, because only 7 projects had been boosted till that time. Does it make sense to you?

**Comment by aminlatifi** [comment]
> Please check this scenario @aminlatifi 1- I'm on a GIVpower tab of a project I select BOOST and complete the process I expect that the boosting list will be updated at the end of the process But this does not happen and I have to refresh the page and it takes time to see the changes
> 
> 2- And one more thing, when a project is boosted by several users, The TOTAL GIVPOWER & PROJECT RANK is displayed as pic below: @alireza-sharifpour @MohammadPCh ![image.png](https://camo.githubusercontent.com/2cd72e9eb6c74ff01a99239a19f0e512430bbc228da7297395c239e5a250d2dd/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f32393835343935392d356263302d346361612d383266662d353235356262613030633465)

@maryjaf We update the list periodically or on certain special events. Updating all the ranking and scoring by every change in the boosts (which can be done by any user) can consume lots of resources and make the system volnurable.

**Comment by maryjaf** [comment]
> > Please check this scenario @aminlatifi 1- I'm on a GIVpower tab of a project I select BOOST and complete the process I expect that the boosting list will be updated at the end of the process But this does not happen and I have to refresh the page and it takes time to see the changes
> > 2- And one more thing, when a project is boosted by several users, The TOTAL GIVPOWER & PROJECT RANK is displayed as pic below: @alireza-sharifpour @MohammadPCh ![image.png](https://camo.githubusercontent.com/2cd72e9eb6c74ff01a99239a19f0e512430bbc228da7297395c239e5a250d2dd/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f32393835343935392d356263302d346361612d383266662d353235356262613030633465)
> 
> @maryjaf We update the list periodically or on certain special events. Updating all the ranking and scoring by every change in the boosts (which can be done by any user) can consume lots of resources and make the system volnurable.

Thanks @aminlatifi  
so 1st scenario is accepted

@MohammadPCh plz check item 2

**Comment by MoeNick** [comment]
@alireza-sharifpour @MohammadPCh is there any updates on this?

**Comment by aminlatifi** [comment]
@divine-comedian @maryjaf 
User rank is fixed
<img width="905" alt="image" src="https://user-images.githubusercontent.com/5684607/190995607-95dc00ea-e44e-4795-9075-4d17b1bcfc3c.png">

**Comment by maryjaf** [comment]
> 2- And one more thing, when a project is boosted by several users, The TOTAL GIVPOWER & PROJECT RANK is displayed as pic below: @alireza-sharifpour @MohammadPCh

Thanks, it's ok now

**Comment by maryjaf** [comment]
The problem of project ranking still exists,and the project project hasn't received any boosts yet has ranked 11
I'll  move this issue to in progress column
@MoeNick @aminlatifi 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/c7c8e21d-65de-42f5-a6d3-9239a944162a)

**Comment by aminlatifi** [comment]
> The problem of project ranking still exists,and the project project hasn't received any boosts yet has ranked 11 I'll move this issue to in progress column @MoeNick @aminlatifi ![image.png](https://camo.githubusercontent.com/2e5d2cd79c0e5d9621acaf41aa02746b49a9acb4f2ac30dafe017b82f68f273d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f63376338653231642d363564652d343266352d613664332d393233396139343431363261)

Actually it's not a bug in developers' view! it means only we have 10 projects with positive allocated power. Hence, if we sort projects based on allocated power, this project will be put in 11th position.
The rank is provided by the API, the database ranks projects based on the value. If we need to show something else, it think the best way is to add a condition in the frontend rather than changing the backend

**Comment by maryjaf** [comment]
> > The problem of project ranking still exists,and the project project hasn't received any boosts yet has ranked 11 I'll move this issue to in progress column @MoeNick @aminlatifi ![image.png](https://camo.githubusercontent.com/2e5d2cd79c0e5d9621acaf41aa02746b49a9acb4f2ac30dafe017b82f68f273d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f63376338653231642d363564652d343266352d613664332d393233396139343431363261)
> 
> Actually it's not a bug in developers' view! it means only we have 10 projects with positive allocated power. Hence, if we sort projects based on allocated power, this project will be put in 11th position. The rank is provided by the API, the database ranks projects based on the value. If we need to show something else, it think the best way is to add a condition in the frontend rather than changing the backend

Thanks for the explanation
I also had a question, what is the difference between a project that has not been boosted and has rank 11 and a project that has not been ranked?
<img width="878" alt="image" src="https://user-images.githubusercontent.com/111529185/191713728-143fe6a4-345d-420d-a936-5e3665637f9a.png">

**Comment by aminlatifi** [comment]
> > > The problem of project ranking still exists,and the project project hasn't received any boosts yet has ranked 11 I'll move this issue to in progress column @MoeNick @aminlatifi ![image.png](https://camo.githubusercontent.com/2e5d2cd79c0e5d9621acaf41aa02746b49a9acb4f2ac30dafe017b82f68f273d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f63376338653231642d363564652d343266352d613664332d393233396139343431363261)
> > 
> > 
> > Actually it's not a bug in developers' view! it means only we have 10 projects with positive allocated power. Hence, if we sort projects based on allocated power, this project will be put in 11th position. The rank is provided by the API, the database ranks projects based on the value. If we need to show something else, it think the best way is to add a condition in the frontend rather than changing the backend
> 
> Thanks for the explanation I also had a question, what is the difference between a project that has not been boosted and has rank 11 and a project that has not been ranked? <img alt="image" width="878" src="https://user-images.githubusercontent.com/111529185/191713728-143fe6a4-345d-420d-a936-5e3665637f9a.png">

All the projects must be ranked based on our backend implementation. Maybe the frontend doesn't show the rank for some other reason (is not verified, etc.) @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
> All the projects must be ranked based on our backend implementation. Maybe the frontend doesn't show the rank for some other reason (is not verified, etc.) @alireza-sharifpour

It seems the problem is because backend sends projectPower: null
![Screen Shot 2022-09-22 at 2 10 02 PM](https://user-images.githubusercontent.com/48887817/191726126-9c44bfbf-48ed-4be8-92ec-8ccbe2b15ec2.png)
@aminlatifi

**Comment by aminlatifi** [comment]
@alireza-sharifpour You are right
@maryjaf it's fixe now. I create this PR https://github.com/Giveth/impact-graph/pull/657

**Comment by maryjaf** [comment]
All figma in this issue have been tested and passed 
and the problem about rank of project that  it hasn't received any boosts yet is checked on issue #762
